# Taps
tap "felixkratz/formulae"
tap "nikitabobko/tap"

# Terminal Only
brew "antidote"
brew "lazygit"
brew "luarocks"
brew "mas"
brew "neovim"
brew "nvm"
brew "poetry"
brew "pyenv"
brew "ripgrep"
brew "rustup"
brew "socat"
brew "starship"
brew "stow"
brew "yarn"
cask "ghostty"
cask "wezterm"

# Not Terminal Only
brew "mpv"
cask "aerospace"
cask "appcleaner"
cask "blackhole-2ch"
cask "chatgpt"
cask "cursor"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "hammerspoon"
cask "hiddenbar"
cask "linear-linear"
cask "loom"
cask "macwhisper"
cask "obs"
cask "orbstack"
cask "postgres-unofficial"
cask "postico"
cask "postman"
cask "raycast"
cask "readdle-spark"
cask "slack"
cask "steam"
cask "superwhisper"
cask "telegram"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vmware-fusion"
cask "webtorrent"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "MeetingBar", id: 1532419400
