notARepository: "quit"
os:
  editPreset: nvim
gui:
  showBottomLine: true
  theme:
    # One Dark theme colors
    activeBorderColor:
      - "#61afef" # Blue
      - bold
    inactiveBorderColor:
      - "#3e4452" # Muted gray
    searchingActiveBorderColor:
      - "#e5c07b" # Yellow
      - bold
    selectedLineBgColor:
      - "#2c323c" # Slightly lighter than background
    selectedRangeBgColor:
      - "#3e4452" # Muted gray
    cherryPickedCommitBgColor:
      - "#56b6c2" # Cyan
    cherryPickedCommitFgColor:
      - "#282c34" # Dark background
    unstagedChangesColor:
      - "#e5c07b" # Yellow
    defaultFgColor:
      - "#abb2bf" # Light gray
    # File status colors
    optionsTextColor:
      - "#61afef" # Blue
  border: rounded
  nerdFontsVersion: "3"
